let soundsFiles = [
    "pads/15 Crystal Palace hoch.mp3",
    "pads/schreipad.mp3",
    "pads/16 Crystal Palace tief.mp3",
    "pads/orch_hoch2.mp3",
    "pads/08 MM Choir In The Clouds.mp3",
    "pads/orch_tief.mp3",
    "pads/01 Andrew's Note.mp3",
    "pads/eines tages-002.mp3",
    "pads/07 Noise Bass.mp3",
    "oneshots/krasser_crackl.mp3",
    "oneshots/krasser_crackl5_hoch2.mp3",
    "oneshots/eines tages-004.mp3",
    "oneshots/schpaloink.mp3",
    "oneshots/schlamp.mp3",
    "oneshots/krasser_crackl2.mp3",
    "oneshots/krasser_crackl4.mp3",
    "oneshots/krasser_crackl5_hoch.mp3",
    "oneshots/klängtz2.mp3",
    "oneshots/14 v9 Crash.mp3",
    "oneshots/krasser_crackl3.mp3",
    "oneshots/langer_schnauzer.mp3",
    "toppings/04 v0 Kick.mp3",
    "toppings/09 FH Cracker.mp3",
    "toppings/12 v1 Clap.mp3",
    "toppings/03 Bleeps and More.mp3",
    "toppings/13 FM Steeldrum.mp3",
    "toppings/05 Polysynthnervös.mp3",
    "toppings/11 Grid Tom 3.mp3",
    "toppings/06 Wedding Rhythm.mp3",
    "toppings/10 Banshee.mp3",
    "toppings/netter_bunsenbrenner.mp3"
];
export default soundsFiles;
